### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by pietmichal** [sebas77/Svelto.ECS#41]
I really love this project. 

Are there any plans for Svelto.ECS to be released as a NuGet package?

**Comment by sebas77** [comment]
Hello! thanks for the message. Do you use Svelto.ECS outside unity? If so I really would like to know more about it

**Comment by pietmichal** [comment]
I am currently considering an ECS library for my MonoGame based project and Svelto looks pragmatic.

Installing third-party libraries through NuGet is much simpler.

I am asking if there are any plans because I couldn't get Svelto running in my project (VS2017 asks to migrate .csproj files and migration fails).

**Comment by sebas77** [comment]
I understood your question, that's why I replied with another question as I am very interested to follow the application of Svelto outside Unity.

At the moment I don't have the time to maintain Svelto outside github, but if you will use it and you like it, you may very well help me in doing so.

If you find any problem in using Svelto outside unity, let me know. Check also Svelto.Tasks, I am working on the version 2.0 right now.
