### ISSUE TITLE
Using with MonoGame

### ISSUE THREAD

**Issue by Blucky87** [sebas77/Svelto.ECS#44]
I am trying to test out this ECS with a simple monogame demo but ran into a problem.
Monogame's [Game](https://docs.microsoft.com/en-us/previous-versions/windows/xna/bb197041%28v%3dxnagamestudio.10%29) Class has the [Update](https://docs.microsoft.com/en-us/previous-versions/windows/xna/bb199616%28v%3dxnagamestudio.10%29) and [Draw](https://docs.microsoft.com/en-us/previous-versions/windows/xna/bb196422%28v%3dxnagamestudio.10%29) methods for the game.

The Update method contains the logic that should be run every frame. The Draw method is run sequentially after the Update is called unless TargetElapsedTime has passed, then it will be skipped.

When setting up a Monogame project to use with Svelto.ECS I would create an EngineRoot with a IEntitySubmissionScheduler that would call a WeakAction's  .Invoke() in the Game's Update method. How should I handle the Game's Draw method?

Does anyone have any experience using this library with Monogame?

**Comment by sebas77** [comment]
probably nobody used it, but I am willing to accompany you in this journey, as I am really interested to see it working with Monogame.

You need two things initially, which I can help you to develop:

first you need a Monogame version of the UnityEntitySubmissionScheduler. As you can see from the SimpleSubmissionEntityViewScheduler all you need to do is a strategy for when to call SubmitEntities;

Svelto.ECS Engines do NOT come with an update loop facility. You can use whatever you want for your loops, however if you check the Svelto.Tasks runners, I reckon it would be quite simple to do a monogame version.

all you need is to create something like UpdateMonoRunner for MonoGame. In order to do it, you will neeed something that works like

UnityCoroutineRunner.StartUpdateCoroutine(_processEnumerator);

but for Mono.

I am here to help if this is too overwhelming. You are the first one using it for Mono, so there is some foundation work to be done.

**Comment by sebas77** [comment]
also @Blucky87 if you can join our chat https://discord.gg/3qAdjDb

**Comment by sebas77** [comment]
To anyone interested in using Svelto.ECS/Tasks with Monogame. As Svelto as some extensions for Unity, it would need some more for Monogame, just to make some things simpler. If anyone reading this issue is willing to work on it, I am willing to help and merge the result in the official branch.
