### ISSUE TITLE
`NativeEntityFactory` cannnot create ExtendibleEntityDescriptors

### ISSUE THREAD

**Issue by Seideun** [sebas77/Svelto.ECS#68]
This is an example entity descriptor:

https://cdn.discordapp.com/attachments/459727475287654401/856964598652731392/unknown.png

And this exception:

https://cdn.discordapp.com/attachments/459727475287654401/856964651114692618/unknown.png

My factory goes like this:

https://cdn.discordapp.com/attachments/459727475287654401/856964728613503056/unknown.png

**Comment by sebas77** [comment]
@Seideun I am not sure if you are still interested in this, but I double checked your issue and I think I misunderstood it. It seems you are trying to create native entities using descriptor that have not unmanaged component types. That is not allowed, in order to use the NativeFactory (which btw should be used only for burst/jobs operations) you need to use only unmanaged components.
